// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkszsgpyaupklpejedfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrc3pzZ3B5YXVwa2xwZWplZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDg1MDksImV4cCI6MjA1ODM4NDUwOX0.IlTixmL3o1PInSS3eYXgURZhVAEgq4MM6Ws_JkxMAYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);